dockedit/urls.py
# from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include
from tree.views import roots, NodeView, cases

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tree", roots, name="root"),
    path("tree/<path:path>/", NodeView.as_view(), name="viewnode"),
    path("cases/<path:path>/", cases, name="cases"),
    path("group/", include("group.urls")),
    path("pinch/", include("pinch.urls")),
]  # + debug_toolbar_urls()

group/urls.py
from django.urls import path

from group.views import roots, NodeView, pinch, cases

app_name = "group"
urlpatterns = [
    path("", roots, name="root"),
    path("pinch", pinch, name="pinch"),
    path("node/<path:path>/", NodeView.as_view(), name="node"),
    path("cases/", cases, name="cases"),
]

pinch/urls.py
from django.urls import path

from pinch.views import roots, NodeView, pinch, cases

app_name = "pinch"
urlpatterns = [
    path("", roots, name="root"),
    path("pinch", pinch, name="pinch"),
    path("node/<path:path>/", NodeView.as_view(), name="node"),
    path("cases/", cases, name="cases"),
]

group/models.py
# from django.db import models

# Create your models here.

group/views.py
import json
from collections import defaultdict

from django import views
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render
from django.utils.decorators import method_decorator

from group.utils import get_tree
from tree.models import EntryText
from tree.utils import get_cases, transpose_respect_longest

import plotly.offline
import plotly.graph_objects as go

# Create your views here.


@staff_member_required
def roots(request):
    G = get_tree()

    nodes_no_incoming = [node for node, degree in G.in_degree() if degree == 0]
    print("Nodes with no incoming edges:", nodes_no_incoming)
    nodes = []
    total = 0
    for node in nodes_no_incoming:
        nodes.append(
            {
                "count": len(G.nodes[node]["cases"]),
                "obj": G.nodes[node]["obj"],
            }
        )
        total += len(G.nodes[node]["cases"])

    return render(request, "group/roots.html", {"nodes": nodes, "total": total})


@method_decorator(staff_member_required, name="dispatch")
class NodeView(views.View):
    def parse_path(self, path):
        prog = []

        G = get_tree()
        hist = []
        node = None
        intp = []
        for p in path.split("/"):
            intp.append(int(p))

            if node is None:
                roots = [
                    no
                    for no, degree in G.in_degree()
                    if degree == 0 and G.nodes[no]["obj"].pk == int(p)
                ]
                assert len(roots) == 1
                node = roots[0]
            else:
                for succ in G.successors(node):
                    if G.nodes[succ]["obj"].pk == int(p):
                        node = succ
            prog.append(
                {
                    "obj": G.nodes[node]["obj"],
                    "path": "/".join(hist + [str(G.nodes[node]["obj"].pk)]),
                    "count": len(G.nodes[node]["cases"]),
                }
            )
            hist.append(str(G.nodes[node]["obj"].pk))
        return G, prog, intp, node

    def get(self, request, path):
        G, prog, intp, node = self.parse_path(path)

        total = 0
        nodes = []
        to = None
        for fr, to in sorted(
            G.out_edges(node), key=lambda x: len(G.nodes[x[1]]["cases"]), reverse=True
        ):
            fig = go.Figure(data=[go.Histogram(x=G.nodes[to]["rdays"])])
            fig.update_layout(
                width=300,  # Width in pixels
                height=100,  # Height in pixels
                margin=dict(
                    l=0,  # Left margin
                    r=0,  # Right margin
                    b=0,  # Bottom margin
                    t=0,  # Top margin
                ),
            )
            graph_div = plotly.offline.plot(
                fig,
                auto_open=False,
                output_type="div",
            )
            figf = go.Figure(data=[go.Histogram(x=G.nodes[to]["fdays"])])
            figf.update_layout(
                width=300,  # Width in pixels
                height=100,  # Height in pixels
                margin=dict(
                    l=0,  # Left margin
                    r=0,  # Right margin
                    b=0,  # Bottom margin
                    t=0,  # Top margin
                ),
            )
            graph_divf = plotly.offline.plot(
                figf,
                auto_open=False,
                output_type="div",
            )
            nodes.append(
                {
                    "count": len(G.nodes[to]["cases"]),
                    "graph": to,
                    "obj": G.nodes[to]["obj"],
                    "rhist": graph_div,
                    "fhist": graph_divf,
                }
            )
            total += len(G.nodes[to]["cases"])
        ended = -1
        if to is not None:
            ended = len(G.nodes[to]["cases"]) - total

        return render(
            request,
            "group/node.html",
            {
                "prog": prog,
                "path": path,
                "nodes": nodes,
                "ended": ended,
                "total": total,
            },
        )


def split_by_elements(A, B):
    # Initialize variables to keep track of the current split start and the result
    result = []
    start = 0

    # Iterate through elements of A to find their positions in B
    for element in A:
        # Find the next occurrence of the element in B after 'start' index
        try:
            index = B.index(element, start)
        except ValueError:
            return None  # In case one of the elements in A is not found in B

        # Append the segment of B from 'start' to this index (exclusive)
        result.append(B[start:index])

        # Update the start index for the next segment to be after the found element
        start = index + 1

    # After the loop, add the remaining elements of B after the last element of A
    result.append(B[start:])

    return result


@staff_member_required
def pinch(request):
    print("get req", request.GET)
    points = []
    for r, val in request.GET.items():
        print(r, val)
        if val == "on":
            try:
                x = tuple(map(int, r.split("_")))
                points.append({"pos": x[0], "obj": EntryText.objects.get(pk=x[1])})
            except Exception as e:
                print(e.__repr__())
                pass
    points = sorted(points, key=lambda p: p["pos"])
    cases = get_cases()

    contains = [p["obj"].text for p in points]

    c = {i: defaultdict(int) for i, _ in enumerate(contains)}
    c[-1] = defaultdict(int)
    sel_case = {i: defaultdict(list) for i, _ in enumerate(contains)}
    sel_case[-1] = defaultdict(list)

    with open("data/groups.json") as f:
        rgrouping = json.load(f)

    grouping = {k: v[1:] if v.startswith("🌱") else v for k, v in rgrouping.items()}

    rdays = [[] for _ in enumerate(contains)]
    fdays = [[] for _ in enumerate(contains)]

    for case in cases:
        it = [
            grouping[entry.text]
            for entry in reversed(case.docket)
            if entry.text in grouping
        ]
        it_full = [entry for entry in reversed(case.docket) if entry.text in grouping]
        # print("it_full", it_full)
        file_date = it_full[0].date
        # print([item in it for item in seqences[variant]["docket"]])
        # contains = [item in it for item in seqences[variant]["docket"]]
        # vals = [o or n for o,n in zip(vals,contains)]
        # continue
        res = split_by_elements(contains, it)
        if res is not None:
            # print(contains)
            # print(res)

            pos = 0
            prev_date = file_date
            for i, sub in enumerate(res[:-1]):
                pos += len(sub)
                # print("get", pos)
                found_elem = it_full[pos]
                pos += 1
                # print(found_elem)
                rdays[i].append((found_elem.date - prev_date).days)
                prev_date = found_elem.date
                fdays[i].append((found_elem.date - file_date).days)

            for i, el in enumerate(res):
                # if len(el) > 0:
                c[i - 1][tuple(el)] += 1
                sel_case[i - 1][tuple(el)].append(case)
            # break

    # print("rdays", rdays)
    # print("fdays", fdays)
    mapping = {}
    for e in EntryText.objects.all():
        mapping[e.text] = e

    hist = 0
    full = [
        [
            (
                [(mapping[entry], hist + hist_add) for hist_add, entry in enumerate(p)],
                c,
                [case.case_number for case in sel],
            )
            for (p, c), (_, sel) in zip(c[-1].items(), sel_case[-1].items())
        ]
    ]
    hist += 100
    hist_idx = 0
    for i, p in enumerate(points):
        fig = go.Figure(data=[go.Histogram(x=rdays[hist_idx])])
        fig.update_layout(
            width=300,  # Width in pixels
            height=100,  # Height in pixels
            margin=dict(
                l=0,  # Left margin
                r=0,  # Right margin
                b=0,  # Bottom margin
                t=0,  # Top margin
            ),
        )
        graph_div = plotly.offline.plot(
            fig,
            auto_open=False,
            output_type="div",
        )

        figf = go.Figure(data=[go.Histogram(x=fdays[hist_idx])])
        figf.update_layout(
            width=300,  # Width in pixels
            height=100,  # Height in pixels
            margin=dict(
                l=0,  # Left margin
                r=0,  # Right margin
                b=0,  # Bottom margin
                t=0,  # Top margin
            ),
        )
        graph_divf = plotly.offline.plot(
            figf,
            auto_open=False,
            output_type="div",
        )

        full.append([p, {"hist": graph_div}, {"hist": graph_divf}])
        hist_idx += 1
        # full.append()
        hist += 200
        sorted_inbetween = sorted(
            list(zip(c[i].items(), sel_case[i].items())),
            key=lambda p: p[0][1],
            reverse=True,
        )
        full.append(
            [
                (
                    [
                        (mapping[entry], hist + hist_add)
                        for hist_add, entry in enumerate(p)
                    ],
                    c,
                    [case.case_number for case in sel],
                )
                for (p, c), (_, sel) in sorted_inbetween
            ]
        )

    # print(full)

    tr = transpose_respect_longest(full)

    return render(request, "group/pinch.html", {"table": tr})


@staff_member_required
def cases(request):
    rel = list(filter(lambda x: x.case_number in request.GET.keys(), get_cases()))

    tr = transpose_respect_longest([list(reversed(c.docket)) for c in rel])
    return render(
        request,
        "group/cases.html",
        {

group/templates/group/cases.html
<html>
<body>
<table style="overflow-x: auto;">
    <tr>
        {% for c in cases %}
            <td  style="min-width: 300px;">{{ c }}</td>
        {% endfor %}
    </tr>
    {% for row in dockets %}
        <tr>
        {% for e in row %}
            <td><b>{{ e.text }}</b><br/>{{ e.extra }}</td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>
</body>
</html>

group/templates/group/node.html
<html>
<body>
<form method="get" action="{% url "group:pinch" %}" >
<table>
    <tr>
        <td><a href="{% url "group:root" %}">Root</a></td>
    </tr>
    {% for p in prog %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><input type="checkbox" name="{{ forloop.counter0 }}_{{ p.obj.pk }}" /> </td>
        <td>{% if p.path %}<a href="{% url "group:node" path=p.path %}">{% else %}<a href="{% url "group:root" %}">{% endif %}{{ p.obj.text }}</a></td>
        <td>{% if p.path and p.count < 50 %}<a href="{% url "cases" path=p.path %}">{{ p.count }}</a>{% else %}{{ p.count }}{% endif %}</td>
    </tr>
    {% endfor %}
</table>
<input type="submit" />
</form>
<table>
<tr>
    <th>label</th>
    <th># cases</th>
</tr>
{% for node in nodes %}
<tr>
<td><a href="{% url "group:node" path=path %}{{ node.obj.pk }}">{{ node.obj.text }}</a></td>
<td>{{ node.count }}</td>
<td>{{ node.rhist | safe }}</td>
<td>{{ node.fhist | safe }}</td>
</tr>
{% endfor %}
<tr>
    <td>total:</td>
    <th>{{ total }}</th>
</tr>
{% if ended > 0 %}
<tr>
    <td>end:</td>
    <th><a href="{% url "cases" path=path %}?ended=1">{{ ended }}</a></th>
</tr>
{% endif %}
</table>

</body>
</html>

group/templates/group/pinch.html
<form  method="get" action="{% url "group:pinch" %}" >
<input type="submit" />
<table border="1" style="overflow-x: auto;">
    {% for row in table %}
        <tr>
            {% for el in row %}
                <td style="min-width: 200px;">{% if el.obj %}<b><input type="checkbox" checked="checked" name="{% widthratio forloop.counter 1 100 %}_{{ el.obj.pk }}" /> {{ el.obj.text }}</b>
                    {% elif el.hist %}{{ el.hist | safe }}
                    {% else %}
                    {% if el %}<b>{% if el.2|length < 50 %}<a href="{% url "group:cases" %}?{{ el.2|join:"&" }}">{{ el.1 }}</a>{% else %}{{ el.1 }}{% endif %} </b>
                        {% for e in el.0 %}
                            <input type="checkbox" name="{{ e.1 }}_{{ e.0.pk }}" /> {{ e.0.text }}<br>
                        {%  empty %}
                            direct
                        {% endfor %}
                        {% endif %}
                    {% endif %}</td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>
</form>

group/templates/group/roots.html
<table>
<tr>
    <th>label</th>
    <th># cases</th>
</tr>
{% for node in nodes %}
<tr>
<td><a href="{% url "group:node" path=node.obj.pk %}">{{ node.obj.text }}</a></td>
<td>{{ node.count }}</td>
</tr>
{% endfor %}
<tr>
    <td></td>
    <th>{{ total }}</th>
</tr>
</table>